### ISSUE TITLE
Change name at some point

### ISSUE THREAD

**Issue by niemasd** [MihirBafna/FAVITESViz#3]
"FAVITESWebsite" works okay for now, but in the future, let's change it to like "FAVITES-VZ" or something describing the fact that it's specifically a tool for visualizing FAVITES output

**Comment by MihirBafna** [comment]
That sounds good I will change it.

Mihir

**Comment by niemasd** [comment]
Maybe FAVITES-VIZ actually, or FAVITESviz or whatever looks the most pleasant and easiest to say out loud
